---
name: Semgrep
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: 15 11 * * *
permissions:
  contents: read
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read         # required by actions/checkout on private repos
      security-events: write # required for SARIF upload
    container:
      image: semgrep/semgrep@sha256:85f9de554201cc891c470774bb93a7f4faf41ea198ddccc34a855b53f7a51443  # v1.127.1

    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d  # v2.16.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - run: semgrep ci --sarif --sarif-output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
          SEMGREP_ENABLE_VERSION_CHECK: 0
          SEMGREP_SEND_METRICS: 'off'
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98  # v4.32.6
        with:
          sarif_file: semgrep.sarif
